openapi: 3.0.3
info:
  title: Task Manager API
  description: A simple API for managing tasks with CRUD operations
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:5001
    description: Development server
  - url: https://keploytaskmanageapi.onrender.com
    description: Production server

paths:
  /api/tasks:
    get:
      summary: Get all tasks
      description: Retrieve a list of all tasks
      operationId: getTasks
      tags:
        - Tasks
      responses:
        '200':
          description: List of tasks retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              example:
                - _id: "507f1f77bcf86cd799439011"
                  title: "Complete project documentation"
                  description: "Write comprehensive documentation for the API"
                  completed: false
                  createdAt: "2024-01-15T10:30:00Z"
                  updatedAt: "2024-01-15T10:30:00Z"
                - _id: "507f1f77bcf86cd799439012"
                  title: "Review code changes"
                  description: "Review pull requests and provide feedback"
                  completed: true
                  createdAt: "2024-01-14T09:15:00Z"
                  updatedAt: "2024-01-15T11:20:00Z"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      summary: Create a new task
      description: Create a new task with the provided details
      operationId: createTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  description: The title of the task
                  example: "Complete project documentation"
                description:
                  type: string
                  description: The description of the task
                  example: "Write comprehensive documentation for the API"
                completed:
                  type: boolean
                  description: Whether the task is completed
                  default: false
                  example: false
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                _id: "507f1f77bcf86cd799439013"
                title: "Complete project documentation"
                description: "Write comprehensive documentation for the API"
                completed: false
                createdAt: "2024-01-15T10:30:00Z"
                updatedAt: "2024-01-15T10:30:00Z"
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: The task ID
        schema:
          type: string
        example: "507f1f77bcf86cd799439011"
    
    put:
      summary: Update a task
      description: Update an existing task by ID
      operationId: updateTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The title of the task
                  example: "Updated project documentation"
                description:
                  type: string
                  description: The description of the task
                  example: "Write comprehensive documentation for the API with examples"
                completed:
                  type: boolean
                  description: Whether the task is completed
                  example: true
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                _id: "507f1f77bcf86cd799439011"
                title: "Updated project documentation"
                description: "Write comprehensive documentation for the API with examples"
                completed: true
                createdAt: "2024-01-15T10:30:00Z"
                updatedAt: "2024-01-15T11:45:00Z"
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      summary: Delete a task
      description: Delete a task by ID
      operationId: deleteTask
      tags:
        - Tasks
      responses:
        '200':
          description: Task deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Task deleted"
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Task:
      type: object
      required:
        - title
      properties:
        _id:
          type: string
          description: The unique identifier for the task
          example: "507f1f77bcf86cd799439011"
        title:
          type: string
          description: The title of the task
          example: "Complete project documentation"
        description:
          type: string
          description: The description of the task
          example: "Write comprehensive documentation for the API"
        completed:
          type: boolean
          description: Whether the task is completed
          default: false
          example: false
        createdAt:
          type: string
          format: date-time
          description: The timestamp when the task was created
          example: "2024-01-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: The timestamp when the task was last updated
          example: "2024-01-15T11:45:00Z"
    
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: "Task not found"
        error:
          type: string
          description: Error type
          example: "ValidationError"

tags:
  - name: Tasks
    description: Operations related to task management 