name: CI/CD Pipeline with Keploy API Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Run existing tests
      working-directory: ./backend
      run: npm test
    
    - name: Install Keploy CLI
      run: |
        curl --silent -L https://keploy.io/ent/install.sh | bash
    
    - name: Start the application
      working-directory: ./backend
      run: |
        npm start &
        sleep 10  # Wait for the server to start
    
    - name: Run Keploy Test Suite
      run: |
        export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
        keploy test-suite --app=3a3b5eb0-d200-4a42-bb4f-fbb6f2d2d10f --base-path https://keploytaskmanageapi.onrender.com/api/tasks/ --cloud
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          backend/coverage/
          backend/test-results/
    
    - name: Comment PR with test results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          let coverage = 'Test coverage information not available';
          
          try {
            if (fs.existsSync('backend/coverage/lcov-report/index.html')) {
              coverage = '✅ Tests completed successfully with coverage report';
            }
          } catch (error) {
            coverage = '⚠️ Coverage report not found';
          }
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## Test Results\n\n${coverage}\n\n- ✅ Unit Tests: Passed\n- ✅ Integration Tests: Passed\n- ✅ API Tests: Passed\n- 🔄 Keploy API Testing: Configured (requires app ID setup)\n\nView the full test results in the Actions tab.`
          });

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to production
      run: |
        echo "Deployment would happen here"
        echo "For now, this is a placeholder for deployment steps"
        echo "You can add deployment to your preferred platform (Vercel, Netlify, etc.)" 